name: Run BrowserStack Tests

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - master  # Change to your default branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests on BrowserStack
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      run: |
        # Assuming you have a pytest setup that works with BrowserStack
        browserstack-sdk pytest -v -s -m sanity --html=reports/report.html

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: reports/report.html
